---
- name: Deploy properties-by-magni
  hosts: raspberrypi
  become: yes
  vars:
    frontend_dir: /opt/properties-by-magni/frontend
    backend_dir: /opt/properties-by-magni/backend
    scraper_dir: /opt/properties-by-magni/scraper
  tasks:
    - name: Ensure required packages are installed
      apt:
        name:
          - git
          - nodejs
          - npm
          - python3
          - python3-venv
          - python3-pip
          - libpq-dev
        state: present
        update_cache: yes

    # --- Properties-by-Magni Repo Setup ---
    - name: Ensure /opt/properties-by-magni directory exists
      ansible.builtin.file:
        path: /opt/properties-by-magni
        state: directory
        mode: '0755'
        owner: raspberrypi
        group: raspberrypi

    - name: Clone or pull the properties-by-magni repository
      git:
        repo: https://github.com/magnimar/properties-by-magni.git
        dest: /opt/properties-by-magni
        version: everything_service
        clone: yes
        update: yes
        force: yes

    - name: Change ownership of cloned properties-by-magni files
      ansible.builtin.file:
        path: /opt/properties-by-magni
        state: directory
        owner: raspberrypi
        group: raspberrypi
        recurse: yes

    # --- Dependencies Installation ---
    - name: Install frontend npm dependencies
      ansible.builtin.shell:
        cmd: npm ci
        chdir: "{{ frontend_dir }}"
      become_user: raspberrypi

    - name: Install backend python dependencies
      pip:
        requirements: "{{ backend_dir }}/requirements.txt"
        virtualenv: "{{ backend_dir }}/venv"
        virtualenv_command: /usr/bin/python3 -m venv
      become_user: raspberrypi

    - name: Install scraper python dependencies
      pip:
        requirements: "{{ scraper_dir }}/requirements.txt"
        virtualenv: "{{ scraper_dir }}/venv"
        virtualenv_command: /usr/bin/python3 -m venv
      become_user: raspberrypi

    # --- Service File Setup & Logging ---
    - name: Ensure log files exist and have correct ownership
      ansible.builtin.file:
        path: "{{ item }}"
        state: touch
        owner: raspberrypi
        group: raspberrypi
        mode: '0644'
      loop:
        - /var/log/frontend.log
        - /var/log/backend.log
        - /var/log/scraper.log

    - name: Copy service files
      ansible.builtin.copy:
        src: "/opt/properties-by-magni/services/{{ item }}"
        dest: "/etc/systemd/system/{{ item }}"
        mode: '0644'
        remote_src: yes
      loop:
        - frontend.service
        - backend.service
        - scraper.service

    - name: Validate systemd file syntax
      ansible.builtin.command:
        cmd: "systemd-analyze verify /etc/systemd/system/{{ item }}"
      loop:
        - frontend.service
        - backend.service
        - scraper.service
      register: systemd_check
      failed_when: systemd_check.rc != 0

    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Enable and restart services
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: restarted
        enabled: yes
      loop:
        - frontend
        - backend
        - scraper
