name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  lint_and_check:
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: [backend, scraper]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ${{ matrix.directory }}/requirements.txt
        pip install ruff black

    - name: Run Ruff Linter
      run: ruff check ${{ matrix.directory }}

    - name: Run Black Formatter Check
      run: black --check ${{ matrix.directory }}

    - name: Compile Python files
      run: python -m compileall ${{ matrix.directory }}
