name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main
      - add_services

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Tailscale
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TS_AUTHKEY }}

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Run Ansible playbook
        run: |
          ansible-playbook devops/ansible/playbook.yml -i devops/ansible/inventory.ini --private-key ${{ secrets.SSH_PRIVATE_KEY }}
